services:
  alpha:
    build: "./alpha"
    ports:
      - "8080:80"

  beta:
    build: "./beta"
    ports:
      - "8081:80"

  # gamma:
  #   build: "./pictures"
  #   # networks:
  #   #   - myprojectnetwork
  #   ports:
  #     - "8082:80"