services:
  alpha:
    build: "./alpha"
    ports:
      - "8080:80"
    volumes:
      - stored_images:/usr/share/nginx/html/images

  beta:
    build: "./beta"
    ports:
      - "8081:80"
    volumes:
      - stored_images:/usr/share/nginx/html/images

  shared-volume:
    build: "./shared-volume"
    volumes:
      - stored_images:/data/images

volumes:
  stored_images: